//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solucion_informatica_Consultorio_Juridico.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abogado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Abogado()
        {
            this.Movimiento_Expediente = new HashSet<Movimiento_Expediente>();
            this.Movimiento_Expediente1 = new HashSet<Movimiento_Expediente>();
        }
    
        public int ab_id { get; set; }
        public int id_estabo { get; set; }
        public int tipb_id { get; set; }
        public string ab_nombres { get; set; }
        public string ab_apellidopat { get; set; }
        public string ab_apellidomat { get; set; }
        public string ab_dni { get; set; }
    
        public virtual Estado_Abogado Estado_Abogado { get; set; }
        public virtual Tipo_Abogado Tipo_Abogado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimiento_Expediente> Movimiento_Expediente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimiento_Expediente> Movimiento_Expediente1 { get; set; }
    }
}
