//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solucion_informatica_Consultorio_Juridico.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class consultoriojurEntities : DbContext
    {
        public consultoriojurEntities()
            : base("name=consultoriojurEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abogado> Abogado { get; set; }
        public virtual DbSet<Anexos> Anexos { get; set; }
        public virtual DbSet<Demandado> Demandado { get; set; }
        public virtual DbSet<Demandante> Demandante { get; set; }
        public virtual DbSet<Documento> Documento { get; set; }
        public virtual DbSet<Estado_Abogado> Estado_Abogado { get; set; }
        public virtual DbSet<Estado_Usu> Estado_Usu { get; set; }
        public virtual DbSet<Expediente> Expediente { get; set; }
        public virtual DbSet<Historial_Juzgado> Historial_Juzgado { get; set; }
        public virtual DbSet<Logueo> Logueo { get; set; }
        public virtual DbSet<Movimiento_Expediente> Movimiento_Expediente { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tip_documento> Tip_documento { get; set; }
        public virtual DbSet<Tipo_Abogado> Tipo_Abogado { get; set; }
        public virtual DbSet<Tipo_Usuario> Tipo_Usuario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<V__lsttipousuarioxtipous> V__lsttipousuarioxtipous { get; set; }
        public virtual DbSet<V_lstabogxestabog> V_lstabogxestabog { get; set; }
        public virtual DbSet<V_lstanexmovexp> V_lstanexmovexp { get; set; }
        public virtual DbSet<V_lstanxnombre> V_lstanxnombre { get; set; }
        public virtual DbSet<V_lstDemtexPers> V_lstDemtexPers { get; set; }
        public virtual DbSet<V_lstDemxPers> V_lstDemxPers { get; set; }
        public virtual DbSet<V_lstdemxreg> V_lstdemxreg { get; set; }
        public virtual DbSet<V_lstdocxexp> V_lstdocxexp { get; set; }
        public virtual DbSet<V_lstDocxnom> V_lstDocxnom { get; set; }
        public virtual DbSet<V_lstDocxnomreal> V_lstDocxnomreal { get; set; }
        public virtual DbSet<V_lstestabg> V_lstestabg { get; set; }
        public virtual DbSet<V_lstestusuxcond> V_lstestusuxcond { get; set; }
        public virtual DbSet<V_lstexpxhistjuzg> V_lstexpxhistjuzg { get; set; }
        public virtual DbSet<V_lstExpxmateria> V_lstExpxmateria { get; set; }
        public virtual DbSet<V_lstexpxmovexp> V_lstexpxmovexp { get; set; }
        public virtual DbSet<V_lstExpxnumero> V_lstExpxnumero { get; set; }
        public virtual DbSet<V_lstHistdeJuzgxdescr> V_lstHistdeJuzgxdescr { get; set; }
        public virtual DbSet<V_lstHistdeJuzgxFechRec> V_lstHistdeJuzgxFechRec { get; set; }
        public virtual DbSet<V_lstHistdeJuzgxFechSol> V_lstHistdeJuzgxFechSol { get; set; }
        public virtual DbSet<V_lstjuzgxexp> V_lstjuzgxexp { get; set; }
        public virtual DbSet<V_lstmovexpxexp> V_lstmovexpxexp { get; set; }
        public virtual DbSet<V_lstpersonaxciudad> V_lstpersonaxciudad { get; set; }
        public virtual DbSet<V_lstpersonaxdepartamento> V_lstpersonaxdepartamento { get; set; }
        public virtual DbSet<V_lstpersonaxprovincia> V_lstpersonaxprovincia { get; set; }
        public virtual DbSet<V_lstperxtipdoc> V_lstperxtipdoc { get; set; }
        public virtual DbSet<V_lsttipabxabo> V_lsttipabxabo { get; set; }
        public virtual DbSet<V_lsttipAbxdef_inc> V_lsttipAbxdef_inc { get; set; }
        public virtual DbSet<V_lsttipAbxestado> V_lsttipAbxestado { get; set; }
        public virtual DbSet<V_lsttipdemxreg> V_lsttipdemxreg { get; set; }
        public virtual DbSet<V_lsttipdocxnom> V_lsttipdocxnom { get; set; }
        public virtual DbSet<V_lsttipousuarioxdescripcion> V_lsttipousuarioxdescripcion { get; set; }
        public virtual DbSet<V_lsttipuxusu> V_lsttipuxusu { get; set; }
        public virtual DbSet<V_lstuserxmovexp> V_lstuserxmovexp { get; set; }
        public virtual DbSet<V_lstusuarioxciudad> V_lstusuarioxciudad { get; set; }
        public virtual DbSet<V_lstusuarioxdepartamento> V_lstusuarioxdepartamento { get; set; }
        public virtual DbSet<V_lstusuarioxprovincia> V_lstusuarioxprovincia { get; set; }
        public virtual DbSet<V_lstxapellidospat> V_lstxapellidospat { get; set; }
        public virtual DbSet<V_lstxdni> V_lstxdni { get; set; }
        public virtual DbSet<V_lstxestado> V_lstxestado { get; set; }
        public virtual DbSet<V_lstxfechaing> V_lstxfechaing { get; set; }
        public virtual DbSet<V_lstxnombres> V_lstxnombres { get; set; }
        public virtual DbSet<V_lstxprogreso> V_lstxprogreso { get; set; }
    
        public virtual int actualizar_abogado(Nullable<int> ab_id, Nullable<int> tipb_id, string ab_nombres, string ab_apellidopat, string ab_apellidomat, Nullable<int> ab_estado, string ab_dni)
        {
            var ab_idParameter = ab_id.HasValue ?
                new ObjectParameter("ab_id", ab_id) :
                new ObjectParameter("ab_id", typeof(int));
    
            var tipb_idParameter = tipb_id.HasValue ?
                new ObjectParameter("tipb_id", tipb_id) :
                new ObjectParameter("tipb_id", typeof(int));
    
            var ab_nombresParameter = ab_nombres != null ?
                new ObjectParameter("ab_nombres", ab_nombres) :
                new ObjectParameter("ab_nombres", typeof(string));
    
            var ab_apellidopatParameter = ab_apellidopat != null ?
                new ObjectParameter("ab_apellidopat", ab_apellidopat) :
                new ObjectParameter("ab_apellidopat", typeof(string));
    
            var ab_apellidomatParameter = ab_apellidomat != null ?
                new ObjectParameter("ab_apellidomat", ab_apellidomat) :
                new ObjectParameter("ab_apellidomat", typeof(string));
    
            var ab_estadoParameter = ab_estado.HasValue ?
                new ObjectParameter("ab_estado", ab_estado) :
                new ObjectParameter("ab_estado", typeof(int));
    
            var ab_dniParameter = ab_dni != null ?
                new ObjectParameter("ab_dni", ab_dni) :
                new ObjectParameter("ab_dni", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("actualizar_abogado", ab_idParameter, tipb_idParameter, ab_nombresParameter, ab_apellidopatParameter, ab_apellidomatParameter, ab_estadoParameter, ab_dniParameter);
        }
    
        public virtual int actualizar_demandado(Nullable<int> demdo_id, Nullable<int> pers_id, string demdo_registro)
        {
            var demdo_idParameter = demdo_id.HasValue ?
                new ObjectParameter("demdo_id", demdo_id) :
                new ObjectParameter("demdo_id", typeof(int));
    
            var pers_idParameter = pers_id.HasValue ?
                new ObjectParameter("pers_id", pers_id) :
                new ObjectParameter("pers_id", typeof(int));
    
            var demdo_registroParameter = demdo_registro != null ?
                new ObjectParameter("demdo_registro", demdo_registro) :
                new ObjectParameter("demdo_registro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("actualizar_demandado", demdo_idParameter, pers_idParameter, demdo_registroParameter);
        }
    
        public virtual int actualizar_demandante(Nullable<int> demte_id, Nullable<int> pers_id, string demte_registro)
        {
            var demte_idParameter = demte_id.HasValue ?
                new ObjectParameter("demte_id", demte_id) :
                new ObjectParameter("demte_id", typeof(int));
    
            var pers_idParameter = pers_id.HasValue ?
                new ObjectParameter("pers_id", pers_id) :
                new ObjectParameter("pers_id", typeof(int));
    
            var demte_registroParameter = demte_registro != null ?
                new ObjectParameter("demte_registro", demte_registro) :
                new ObjectParameter("demte_registro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("actualizar_demandante", demte_idParameter, pers_idParameter, demte_registroParameter);
        }
    
        public virtual int actualizar_doc(Nullable<int> doc_id, string doc_nombre, string doc_nombrereal, byte[] doc_documento, Nullable<System.DateTime> doc_fecha)
        {
            var doc_idParameter = doc_id.HasValue ?
                new ObjectParameter("doc_id", doc_id) :
                new ObjectParameter("doc_id", typeof(int));
    
            var doc_nombreParameter = doc_nombre != null ?
                new ObjectParameter("doc_nombre", doc_nombre) :
                new ObjectParameter("doc_nombre", typeof(string));
    
            var doc_nombrerealParameter = doc_nombrereal != null ?
                new ObjectParameter("doc_nombrereal", doc_nombrereal) :
                new ObjectParameter("doc_nombrereal", typeof(string));
    
            var doc_documentoParameter = doc_documento != null ?
                new ObjectParameter("doc_documento", doc_documento) :
                new ObjectParameter("doc_documento", typeof(byte[]));
    
            var doc_fechaParameter = doc_fecha.HasValue ?
                new ObjectParameter("doc_fecha", doc_fecha) :
                new ObjectParameter("doc_fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("actualizar_doc", doc_idParameter, doc_nombreParameter, doc_nombrerealParameter, doc_documentoParameter, doc_fechaParameter);
        }
    
        public virtual int actualizar_Estabog(Nullable<int> id_estabo, string estabog)
        {
            var id_estaboParameter = id_estabo.HasValue ?
                new ObjectParameter("id_estabo", id_estabo) :
                new ObjectParameter("id_estabo", typeof(int));
    
            var estabogParameter = estabog != null ?
                new ObjectParameter("estabog", estabog) :
                new ObjectParameter("estabog", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("actualizar_Estabog", id_estaboParameter, estabogParameter);
        }
    
        public virtual int actualizar_Estusu(Nullable<int> id_estusu, string est_condi)
        {
            var id_estusuParameter = id_estusu.HasValue ?
                new ObjectParameter("id_estusu", id_estusu) :
                new ObjectParameter("id_estusu", typeof(int));
    
            var est_condiParameter = est_condi != null ?
                new ObjectParameter("est_condi", est_condi) :
                new ObjectParameter("est_condi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("actualizar_Estusu", id_estusuParameter, est_condiParameter);
        }
    
        public virtual int actualizar_exp(Nullable<int> exp_id, Nullable<int> movexp, Nullable<int> juzg_id, Nullable<int> doc, string exp_nrosentencia, string exp_expediente, string exp_secrejuzg, Nullable<System.DateTime> exp_fechainicio, string exp_materia, string exp_resolucionnro, string exp_ciudad, string exp_fecha, string exp_vistos)
        {
            var exp_idParameter = exp_id.HasValue ?
                new ObjectParameter("exp_id", exp_id) :
                new ObjectParameter("exp_id", typeof(int));
    
            var movexpParameter = movexp.HasValue ?
                new ObjectParameter("movexp", movexp) :
                new ObjectParameter("movexp", typeof(int));
    
            var juzg_idParameter = juzg_id.HasValue ?
                new ObjectParameter("juzg_id", juzg_id) :
                new ObjectParameter("juzg_id", typeof(int));
    
            var docParameter = doc.HasValue ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(int));
    
            var exp_nrosentenciaParameter = exp_nrosentencia != null ?
                new ObjectParameter("exp_nrosentencia", exp_nrosentencia) :
                new ObjectParameter("exp_nrosentencia", typeof(string));
    
            var exp_expedienteParameter = exp_expediente != null ?
                new ObjectParameter("exp_expediente", exp_expediente) :
                new ObjectParameter("exp_expediente", typeof(string));
    
            var exp_secrejuzgParameter = exp_secrejuzg != null ?
                new ObjectParameter("exp_secrejuzg", exp_secrejuzg) :
                new ObjectParameter("exp_secrejuzg", typeof(string));
    
            var exp_fechainicioParameter = exp_fechainicio.HasValue ?
                new ObjectParameter("exp_fechainicio", exp_fechainicio) :
                new ObjectParameter("exp_fechainicio", typeof(System.DateTime));
    
            var exp_materiaParameter = exp_materia != null ?
                new ObjectParameter("exp_materia", exp_materia) :
                new ObjectParameter("exp_materia", typeof(string));
    
            var exp_resolucionnroParameter = exp_resolucionnro != null ?
                new ObjectParameter("exp_resolucionnro", exp_resolucionnro) :
                new ObjectParameter("exp_resolucionnro", typeof(string));
    
            var exp_ciudadParameter = exp_ciudad != null ?
                new ObjectParameter("exp_ciudad", exp_ciudad) :
                new ObjectParameter("exp_ciudad", typeof(string));
    
            var exp_fechaParameter = exp_fecha != null ?
                new ObjectParameter("exp_fecha", exp_fecha) :
                new ObjectParameter("exp_fecha", typeof(string));
    
            var exp_vistosParameter = exp_vistos != null ?
                new ObjectParameter("exp_vistos", exp_vistos) :
                new ObjectParameter("exp_vistos", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("actualizar_exp", exp_idParameter, movexpParameter, juzg_idParameter, docParameter, exp_nrosentenciaParameter, exp_expedienteParameter, exp_secrejuzgParameter, exp_fechainicioParameter, exp_materiaParameter, exp_resolucionnroParameter, exp_ciudadParameter, exp_fechaParameter, exp_vistosParameter);
        }
    
        public virtual int actualizar_HisJuz(Nullable<int> juzg_id, string juzg_descripcion, Nullable<System.DateTime> juzg_fecharecepcion, string juzg_pronunciamiento, Nullable<System.DateTime> juzg_fechaderivacion, Nullable<System.DateTime> juzg_fechaemisionresol, Nullable<System.DateTime> juzg_fechanotificacion, Nullable<System.DateTime> juzg_fechasolucion)
        {
            var juzg_idParameter = juzg_id.HasValue ?
                new ObjectParameter("juzg_id", juzg_id) :
                new ObjectParameter("juzg_id", typeof(int));
    
            var juzg_descripcionParameter = juzg_descripcion != null ?
                new ObjectParameter("juzg_descripcion", juzg_descripcion) :
                new ObjectParameter("juzg_descripcion", typeof(string));
    
            var juzg_fecharecepcionParameter = juzg_fecharecepcion.HasValue ?
                new ObjectParameter("juzg_fecharecepcion", juzg_fecharecepcion) :
                new ObjectParameter("juzg_fecharecepcion", typeof(System.DateTime));
    
            var juzg_pronunciamientoParameter = juzg_pronunciamiento != null ?
                new ObjectParameter("juzg_pronunciamiento", juzg_pronunciamiento) :
                new ObjectParameter("juzg_pronunciamiento", typeof(string));
    
            var juzg_fechaderivacionParameter = juzg_fechaderivacion.HasValue ?
                new ObjectParameter("juzg_fechaderivacion", juzg_fechaderivacion) :
                new ObjectParameter("juzg_fechaderivacion", typeof(System.DateTime));
    
            var juzg_fechaemisionresolParameter = juzg_fechaemisionresol.HasValue ?
                new ObjectParameter("juzg_fechaemisionresol", juzg_fechaemisionresol) :
                new ObjectParameter("juzg_fechaemisionresol", typeof(System.DateTime));
    
            var juzg_fechanotificacionParameter = juzg_fechanotificacion.HasValue ?
                new ObjectParameter("juzg_fechanotificacion", juzg_fechanotificacion) :
                new ObjectParameter("juzg_fechanotificacion", typeof(System.DateTime));
    
            var juzg_fechasolucionParameter = juzg_fechasolucion.HasValue ?
                new ObjectParameter("juzg_fechasolucion", juzg_fechasolucion) :
                new ObjectParameter("juzg_fechasolucion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("actualizar_HisJuz", juzg_idParameter, juzg_descripcionParameter, juzg_fecharecepcionParameter, juzg_pronunciamientoParameter, juzg_fechaderivacionParameter, juzg_fechaemisionresolParameter, juzg_fechanotificacionParameter, juzg_fechasolucionParameter);
        }
    
        public virtual int actualizar_MovExp(Nullable<int> movexp_id, Nullable<int> ab_id, Nullable<int> usu_id, Nullable<int> demte_id, Nullable<int> demdo_id, Nullable<int> anexo_id, string movexp_asunto, Nullable<System.DateTime> movexp_fechaing, string movexp_estado, string movexp_progreso, string movexp_cantfolios, string movexp_descripcion)
        {
            var movexp_idParameter = movexp_id.HasValue ?
                new ObjectParameter("movexp_id", movexp_id) :
                new ObjectParameter("movexp_id", typeof(int));
    
            var ab_idParameter = ab_id.HasValue ?
                new ObjectParameter("ab_id", ab_id) :
                new ObjectParameter("ab_id", typeof(int));
    
            var usu_idParameter = usu_id.HasValue ?
                new ObjectParameter("usu_id", usu_id) :
                new ObjectParameter("usu_id", typeof(int));
    
            var demte_idParameter = demte_id.HasValue ?
                new ObjectParameter("demte_id", demte_id) :
                new ObjectParameter("demte_id", typeof(int));
    
            var demdo_idParameter = demdo_id.HasValue ?
                new ObjectParameter("demdo_id", demdo_id) :
                new ObjectParameter("demdo_id", typeof(int));
    
            var anexo_idParameter = anexo_id.HasValue ?
                new ObjectParameter("anexo_id", anexo_id) :
                new ObjectParameter("anexo_id", typeof(int));
    
            var movexp_asuntoParameter = movexp_asunto != null ?
                new ObjectParameter("movexp_asunto", movexp_asunto) :
                new ObjectParameter("movexp_asunto", typeof(string));
    
            var movexp_fechaingParameter = movexp_fechaing.HasValue ?
                new ObjectParameter("movexp_fechaing", movexp_fechaing) :
                new ObjectParameter("movexp_fechaing", typeof(System.DateTime));
    
            var movexp_estadoParameter = movexp_estado != null ?
                new ObjectParameter("movexp_estado", movexp_estado) :
                new ObjectParameter("movexp_estado", typeof(string));
    
            var movexp_progresoParameter = movexp_progreso != null ?
                new ObjectParameter("movexp_progreso", movexp_progreso) :
                new ObjectParameter("movexp_progreso", typeof(string));
    
            var movexp_cantfoliosParameter = movexp_cantfolios != null ?
                new ObjectParameter("movexp_cantfolios", movexp_cantfolios) :
                new ObjectParameter("movexp_cantfolios", typeof(string));
    
            var movexp_descripcionParameter = movexp_descripcion != null ?
                new ObjectParameter("movexp_descripcion", movexp_descripcion) :
                new ObjectParameter("movexp_descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("actualizar_MovExp", movexp_idParameter, ab_idParameter, usu_idParameter, demte_idParameter, demdo_idParameter, anexo_idParameter, movexp_asuntoParameter, movexp_fechaingParameter, movexp_estadoParameter, movexp_progresoParameter, movexp_cantfoliosParameter, movexp_descripcionParameter);
        }
    
        public virtual int actualizar_pers(Nullable<int> pers_id, string pers_nombres, string pers_ciudad, string pers_provincia, string pers_departamento, string pers_ubigeo, string pers_domlegal, string pers_telefono, string pers_email, Nullable<int> id_tipdoc, Nullable<decimal> pers_numdoc)
        {
            var pers_idParameter = pers_id.HasValue ?
                new ObjectParameter("pers_id", pers_id) :
                new ObjectParameter("pers_id", typeof(int));
    
            var pers_nombresParameter = pers_nombres != null ?
                new ObjectParameter("pers_nombres", pers_nombres) :
                new ObjectParameter("pers_nombres", typeof(string));
    
            var pers_ciudadParameter = pers_ciudad != null ?
                new ObjectParameter("pers_ciudad", pers_ciudad) :
                new ObjectParameter("pers_ciudad", typeof(string));
    
            var pers_provinciaParameter = pers_provincia != null ?
                new ObjectParameter("pers_provincia", pers_provincia) :
                new ObjectParameter("pers_provincia", typeof(string));
    
            var pers_departamentoParameter = pers_departamento != null ?
                new ObjectParameter("pers_departamento", pers_departamento) :
                new ObjectParameter("pers_departamento", typeof(string));
    
            var pers_ubigeoParameter = pers_ubigeo != null ?
                new ObjectParameter("pers_ubigeo", pers_ubigeo) :
                new ObjectParameter("pers_ubigeo", typeof(string));
    
            var pers_domlegalParameter = pers_domlegal != null ?
                new ObjectParameter("pers_domlegal", pers_domlegal) :
                new ObjectParameter("pers_domlegal", typeof(string));
    
            var pers_telefonoParameter = pers_telefono != null ?
                new ObjectParameter("pers_telefono", pers_telefono) :
                new ObjectParameter("pers_telefono", typeof(string));
    
            var pers_emailParameter = pers_email != null ?
                new ObjectParameter("pers_email", pers_email) :
                new ObjectParameter("pers_email", typeof(string));
    
            var id_tipdocParameter = id_tipdoc.HasValue ?
                new ObjectParameter("id_tipdoc", id_tipdoc) :
                new ObjectParameter("id_tipdoc", typeof(int));
    
            var pers_numdocParameter = pers_numdoc.HasValue ?
                new ObjectParameter("pers_numdoc", pers_numdoc) :
                new ObjectParameter("pers_numdoc", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("actualizar_pers", pers_idParameter, pers_nombresParameter, pers_ciudadParameter, pers_provinciaParameter, pers_departamentoParameter, pers_ubigeoParameter, pers_domlegalParameter, pers_telefonoParameter, pers_emailParameter, id_tipdocParameter, pers_numdocParameter);
        }
    
        public virtual int actualizar_TipAbg(Nullable<int> tipb_id, string tipb_def_inc, string tipb_estado, string tipb_descripcion)
        {
            var tipb_idParameter = tipb_id.HasValue ?
                new ObjectParameter("tipb_id", tipb_id) :
                new ObjectParameter("tipb_id", typeof(int));
    
            var tipb_def_incParameter = tipb_def_inc != null ?
                new ObjectParameter("tipb_def_inc", tipb_def_inc) :
                new ObjectParameter("tipb_def_inc", typeof(string));
    
            var tipb_estadoParameter = tipb_estado != null ?
                new ObjectParameter("tipb_estado", tipb_estado) :
                new ObjectParameter("tipb_estado", typeof(string));
    
            var tipb_descripcionParameter = tipb_descripcion != null ?
                new ObjectParameter("tipb_descripcion", tipb_descripcion) :
                new ObjectParameter("tipb_descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("actualizar_TipAbg", tipb_idParameter, tipb_def_incParameter, tipb_estadoParameter, tipb_descripcionParameter);
        }
    
        public virtual int actualizar_Tipodoc(Nullable<int> id_tipdoc, string tipdoc_nom)
        {
            var id_tipdocParameter = id_tipdoc.HasValue ?
                new ObjectParameter("id_tipdoc", id_tipdoc) :
                new ObjectParameter("id_tipdoc", typeof(int));
    
            var tipdoc_nomParameter = tipdoc_nom != null ?
                new ObjectParameter("tipdoc_nom", tipdoc_nom) :
                new ObjectParameter("tipdoc_nom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("actualizar_Tipodoc", id_tipdocParameter, tipdoc_nomParameter);
        }
    
        public virtual int actualizar_TipUsu(Nullable<int> tipusu_id, string tipusu_tipousuario, string tipusu_descripcion)
        {
            var tipusu_idParameter = tipusu_id.HasValue ?
                new ObjectParameter("tipusu_id", tipusu_id) :
                new ObjectParameter("tipusu_id", typeof(int));
    
            var tipusu_tipousuarioParameter = tipusu_tipousuario != null ?
                new ObjectParameter("tipusu_tipousuario", tipusu_tipousuario) :
                new ObjectParameter("tipusu_tipousuario", typeof(string));
    
            var tipusu_descripcionParameter = tipusu_descripcion != null ?
                new ObjectParameter("tipusu_descripcion", tipusu_descripcion) :
                new ObjectParameter("tipusu_descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("actualizar_TipUsu", tipusu_idParameter, tipusu_tipousuarioParameter, tipusu_descripcionParameter);
        }
    
        public virtual int actualizar_Usu(Nullable<int> usu_id, Nullable<int> tipusu_id, string usu_dni, string usu_nombres, string usu_apellidopat, string usu_apellidomat, string usu_telefono, string usu_direccion, string usu_sexo, string usu_correo, string usu_estadocivil, Nullable<System.DateTime> usu_fechanac, string usu_ciudad, string usu_provincia, Nullable<int> id_estusu, string usu_departamento)
        {
            var usu_idParameter = usu_id.HasValue ?
                new ObjectParameter("usu_id", usu_id) :
                new ObjectParameter("usu_id", typeof(int));
    
            var tipusu_idParameter = tipusu_id.HasValue ?
                new ObjectParameter("tipusu_id", tipusu_id) :
                new ObjectParameter("tipusu_id", typeof(int));
    
            var usu_dniParameter = usu_dni != null ?
                new ObjectParameter("usu_dni", usu_dni) :
                new ObjectParameter("usu_dni", typeof(string));
    
            var usu_nombresParameter = usu_nombres != null ?
                new ObjectParameter("usu_nombres", usu_nombres) :
                new ObjectParameter("usu_nombres", typeof(string));
    
            var usu_apellidopatParameter = usu_apellidopat != null ?
                new ObjectParameter("usu_apellidopat", usu_apellidopat) :
                new ObjectParameter("usu_apellidopat", typeof(string));
    
            var usu_apellidomatParameter = usu_apellidomat != null ?
                new ObjectParameter("usu_apellidomat", usu_apellidomat) :
                new ObjectParameter("usu_apellidomat", typeof(string));
    
            var usu_telefonoParameter = usu_telefono != null ?
                new ObjectParameter("usu_telefono", usu_telefono) :
                new ObjectParameter("usu_telefono", typeof(string));
    
            var usu_direccionParameter = usu_direccion != null ?
                new ObjectParameter("usu_direccion", usu_direccion) :
                new ObjectParameter("usu_direccion", typeof(string));
    
            var usu_sexoParameter = usu_sexo != null ?
                new ObjectParameter("usu_sexo", usu_sexo) :
                new ObjectParameter("usu_sexo", typeof(string));
    
            var usu_correoParameter = usu_correo != null ?
                new ObjectParameter("usu_correo", usu_correo) :
                new ObjectParameter("usu_correo", typeof(string));
    
            var usu_estadocivilParameter = usu_estadocivil != null ?
                new ObjectParameter("usu_estadocivil", usu_estadocivil) :
                new ObjectParameter("usu_estadocivil", typeof(string));
    
            var usu_fechanacParameter = usu_fechanac.HasValue ?
                new ObjectParameter("usu_fechanac", usu_fechanac) :
                new ObjectParameter("usu_fechanac", typeof(System.DateTime));
    
            var usu_ciudadParameter = usu_ciudad != null ?
                new ObjectParameter("usu_ciudad", usu_ciudad) :
                new ObjectParameter("usu_ciudad", typeof(string));
    
            var usu_provinciaParameter = usu_provincia != null ?
                new ObjectParameter("usu_provincia", usu_provincia) :
                new ObjectParameter("usu_provincia", typeof(string));
    
            var id_estusuParameter = id_estusu.HasValue ?
                new ObjectParameter("id_estusu", id_estusu) :
                new ObjectParameter("id_estusu", typeof(int));
    
            var usu_departamentoParameter = usu_departamento != null ?
                new ObjectParameter("usu_departamento", usu_departamento) :
                new ObjectParameter("usu_departamento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("actualizar_Usu", usu_idParameter, tipusu_idParameter, usu_dniParameter, usu_nombresParameter, usu_apellidopatParameter, usu_apellidomatParameter, usu_telefonoParameter, usu_direccionParameter, usu_sexoParameter, usu_correoParameter, usu_estadocivilParameter, usu_fechanacParameter, usu_ciudadParameter, usu_provinciaParameter, id_estusuParameter, usu_departamentoParameter);
        }
    
        public virtual int ActualizarAnexos(Nullable<int> id_anexo, string anexo_nombre, string anexo_nombrereal, byte[] anexo_documento, Nullable<System.DateTime> anexo_fecha)
        {
            var id_anexoParameter = id_anexo.HasValue ?
                new ObjectParameter("id_anexo", id_anexo) :
                new ObjectParameter("id_anexo", typeof(int));
    
            var anexo_nombreParameter = anexo_nombre != null ?
                new ObjectParameter("anexo_nombre", anexo_nombre) :
                new ObjectParameter("anexo_nombre", typeof(string));
    
            var anexo_nombrerealParameter = anexo_nombrereal != null ?
                new ObjectParameter("anexo_nombrereal", anexo_nombrereal) :
                new ObjectParameter("anexo_nombrereal", typeof(string));
    
            var anexo_documentoParameter = anexo_documento != null ?
                new ObjectParameter("anexo_documento", anexo_documento) :
                new ObjectParameter("anexo_documento", typeof(byte[]));
    
            var anexo_fechaParameter = anexo_fecha.HasValue ?
                new ObjectParameter("anexo_fecha", anexo_fecha) :
                new ObjectParameter("anexo_fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarAnexos", id_anexoParameter, anexo_nombreParameter, anexo_nombrerealParameter, anexo_documentoParameter, anexo_fechaParameter);
        }
    
        public virtual int insertar_Abogado(Nullable<int> ab_id, Nullable<int> tipb_id, string ab_nombres, string ab_apellidopat, string ab_apellidomat, Nullable<int> ab_estado, string ab_dni)
        {
            var ab_idParameter = ab_id.HasValue ?
                new ObjectParameter("ab_id", ab_id) :
                new ObjectParameter("ab_id", typeof(int));
    
            var tipb_idParameter = tipb_id.HasValue ?
                new ObjectParameter("tipb_id", tipb_id) :
                new ObjectParameter("tipb_id", typeof(int));
    
            var ab_nombresParameter = ab_nombres != null ?
                new ObjectParameter("ab_nombres", ab_nombres) :
                new ObjectParameter("ab_nombres", typeof(string));
    
            var ab_apellidopatParameter = ab_apellidopat != null ?
                new ObjectParameter("ab_apellidopat", ab_apellidopat) :
                new ObjectParameter("ab_apellidopat", typeof(string));
    
            var ab_apellidomatParameter = ab_apellidomat != null ?
                new ObjectParameter("ab_apellidomat", ab_apellidomat) :
                new ObjectParameter("ab_apellidomat", typeof(string));
    
            var ab_estadoParameter = ab_estado.HasValue ?
                new ObjectParameter("ab_estado", ab_estado) :
                new ObjectParameter("ab_estado", typeof(int));
    
            var ab_dniParameter = ab_dni != null ?
                new ObjectParameter("ab_dni", ab_dni) :
                new ObjectParameter("ab_dni", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_Abogado", ab_idParameter, tipb_idParameter, ab_nombresParameter, ab_apellidopatParameter, ab_apellidomatParameter, ab_estadoParameter, ab_dniParameter);
        }
    
        public virtual int insertar_demandado(Nullable<int> demdo_id, Nullable<int> pers_id, Nullable<int> demdo_registro)
        {
            var demdo_idParameter = demdo_id.HasValue ?
                new ObjectParameter("demdo_id", demdo_id) :
                new ObjectParameter("demdo_id", typeof(int));
    
            var pers_idParameter = pers_id.HasValue ?
                new ObjectParameter("pers_id", pers_id) :
                new ObjectParameter("pers_id", typeof(int));
    
            var demdo_registroParameter = demdo_registro.HasValue ?
                new ObjectParameter("demdo_registro", demdo_registro) :
                new ObjectParameter("demdo_registro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_demandado", demdo_idParameter, pers_idParameter, demdo_registroParameter);
        }
    
        public virtual int insertar_demandante(Nullable<int> demte_id, Nullable<int> pers_id, string demte_registro)
        {
            var demte_idParameter = demte_id.HasValue ?
                new ObjectParameter("demte_id", demte_id) :
                new ObjectParameter("demte_id", typeof(int));
    
            var pers_idParameter = pers_id.HasValue ?
                new ObjectParameter("pers_id", pers_id) :
                new ObjectParameter("pers_id", typeof(int));
    
            var demte_registroParameter = demte_registro != null ?
                new ObjectParameter("demte_registro", demte_registro) :
                new ObjectParameter("demte_registro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_demandante", demte_idParameter, pers_idParameter, demte_registroParameter);
        }
    
        public virtual int insertar_doc(Nullable<int> doc_id, string doc_nombre, string doc_nombrereal, byte[] doc_documento, Nullable<System.DateTime> doc_fecha)
        {
            var doc_idParameter = doc_id.HasValue ?
                new ObjectParameter("doc_id", doc_id) :
                new ObjectParameter("doc_id", typeof(int));
    
            var doc_nombreParameter = doc_nombre != null ?
                new ObjectParameter("doc_nombre", doc_nombre) :
                new ObjectParameter("doc_nombre", typeof(string));
    
            var doc_nombrerealParameter = doc_nombrereal != null ?
                new ObjectParameter("doc_nombrereal", doc_nombrereal) :
                new ObjectParameter("doc_nombrereal", typeof(string));
    
            var doc_documentoParameter = doc_documento != null ?
                new ObjectParameter("doc_documento", doc_documento) :
                new ObjectParameter("doc_documento", typeof(byte[]));
    
            var doc_fechaParameter = doc_fecha.HasValue ?
                new ObjectParameter("doc_fecha", doc_fecha) :
                new ObjectParameter("doc_fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_doc", doc_idParameter, doc_nombreParameter, doc_nombrerealParameter, doc_documentoParameter, doc_fechaParameter);
        }
    
        public virtual int insertar_Estabog(Nullable<int> id_estabo, string estabog)
        {
            var id_estaboParameter = id_estabo.HasValue ?
                new ObjectParameter("id_estabo", id_estabo) :
                new ObjectParameter("id_estabo", typeof(int));
    
            var estabogParameter = estabog != null ?
                new ObjectParameter("estabog", estabog) :
                new ObjectParameter("estabog", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_Estabog", id_estaboParameter, estabogParameter);
        }
    
        public virtual int insertar_Estusu(Nullable<int> id_estusu, string est_condi)
        {
            var id_estusuParameter = id_estusu.HasValue ?
                new ObjectParameter("id_estusu", id_estusu) :
                new ObjectParameter("id_estusu", typeof(int));
    
            var est_condiParameter = est_condi != null ?
                new ObjectParameter("est_condi", est_condi) :
                new ObjectParameter("est_condi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_Estusu", id_estusuParameter, est_condiParameter);
        }
    
        public virtual int insertar_exp(Nullable<int> exp_id, Nullable<int> movexp, Nullable<int> juzg_id, Nullable<int> doc, string exp_nrosentencia, string exp_expediente, string exp_secrejuzg, Nullable<System.DateTime> exp_fechainicio, string exp_materia, string exp_resolucionnro, string exp_ciudad, string exp_fecha, string exp_vistos)
        {
            var exp_idParameter = exp_id.HasValue ?
                new ObjectParameter("exp_id", exp_id) :
                new ObjectParameter("exp_id", typeof(int));
    
            var movexpParameter = movexp.HasValue ?
                new ObjectParameter("movexp", movexp) :
                new ObjectParameter("movexp", typeof(int));
    
            var juzg_idParameter = juzg_id.HasValue ?
                new ObjectParameter("juzg_id", juzg_id) :
                new ObjectParameter("juzg_id", typeof(int));
    
            var docParameter = doc.HasValue ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(int));
    
            var exp_nrosentenciaParameter = exp_nrosentencia != null ?
                new ObjectParameter("exp_nrosentencia", exp_nrosentencia) :
                new ObjectParameter("exp_nrosentencia", typeof(string));
    
            var exp_expedienteParameter = exp_expediente != null ?
                new ObjectParameter("exp_expediente", exp_expediente) :
                new ObjectParameter("exp_expediente", typeof(string));
    
            var exp_secrejuzgParameter = exp_secrejuzg != null ?
                new ObjectParameter("exp_secrejuzg", exp_secrejuzg) :
                new ObjectParameter("exp_secrejuzg", typeof(string));
    
            var exp_fechainicioParameter = exp_fechainicio.HasValue ?
                new ObjectParameter("exp_fechainicio", exp_fechainicio) :
                new ObjectParameter("exp_fechainicio", typeof(System.DateTime));
    
            var exp_materiaParameter = exp_materia != null ?
                new ObjectParameter("exp_materia", exp_materia) :
                new ObjectParameter("exp_materia", typeof(string));
    
            var exp_resolucionnroParameter = exp_resolucionnro != null ?
                new ObjectParameter("exp_resolucionnro", exp_resolucionnro) :
                new ObjectParameter("exp_resolucionnro", typeof(string));
    
            var exp_ciudadParameter = exp_ciudad != null ?
                new ObjectParameter("exp_ciudad", exp_ciudad) :
                new ObjectParameter("exp_ciudad", typeof(string));
    
            var exp_fechaParameter = exp_fecha != null ?
                new ObjectParameter("exp_fecha", exp_fecha) :
                new ObjectParameter("exp_fecha", typeof(string));
    
            var exp_vistosParameter = exp_vistos != null ?
                new ObjectParameter("exp_vistos", exp_vistos) :
                new ObjectParameter("exp_vistos", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_exp", exp_idParameter, movexpParameter, juzg_idParameter, docParameter, exp_nrosentenciaParameter, exp_expedienteParameter, exp_secrejuzgParameter, exp_fechainicioParameter, exp_materiaParameter, exp_resolucionnroParameter, exp_ciudadParameter, exp_fechaParameter, exp_vistosParameter);
        }
    
        public virtual int insertar_HisJuz(Nullable<int> juzg_id, string juzg_descripcion, Nullable<System.DateTime> juzg_fecharecepcion, string juzg_pronunciamiento, Nullable<System.DateTime> juzg_fechaderivacion, Nullable<System.DateTime> juzg_fechaemisionresol, Nullable<System.DateTime> juzg_fechanotificacion, Nullable<System.DateTime> juzg_fechasolucion)
        {
            var juzg_idParameter = juzg_id.HasValue ?
                new ObjectParameter("juzg_id", juzg_id) :
                new ObjectParameter("juzg_id", typeof(int));
    
            var juzg_descripcionParameter = juzg_descripcion != null ?
                new ObjectParameter("juzg_descripcion", juzg_descripcion) :
                new ObjectParameter("juzg_descripcion", typeof(string));
    
            var juzg_fecharecepcionParameter = juzg_fecharecepcion.HasValue ?
                new ObjectParameter("juzg_fecharecepcion", juzg_fecharecepcion) :
                new ObjectParameter("juzg_fecharecepcion", typeof(System.DateTime));
    
            var juzg_pronunciamientoParameter = juzg_pronunciamiento != null ?
                new ObjectParameter("juzg_pronunciamiento", juzg_pronunciamiento) :
                new ObjectParameter("juzg_pronunciamiento", typeof(string));
    
            var juzg_fechaderivacionParameter = juzg_fechaderivacion.HasValue ?
                new ObjectParameter("juzg_fechaderivacion", juzg_fechaderivacion) :
                new ObjectParameter("juzg_fechaderivacion", typeof(System.DateTime));
    
            var juzg_fechaemisionresolParameter = juzg_fechaemisionresol.HasValue ?
                new ObjectParameter("juzg_fechaemisionresol", juzg_fechaemisionresol) :
                new ObjectParameter("juzg_fechaemisionresol", typeof(System.DateTime));
    
            var juzg_fechanotificacionParameter = juzg_fechanotificacion.HasValue ?
                new ObjectParameter("juzg_fechanotificacion", juzg_fechanotificacion) :
                new ObjectParameter("juzg_fechanotificacion", typeof(System.DateTime));
    
            var juzg_fechasolucionParameter = juzg_fechasolucion.HasValue ?
                new ObjectParameter("juzg_fechasolucion", juzg_fechasolucion) :
                new ObjectParameter("juzg_fechasolucion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_HisJuz", juzg_idParameter, juzg_descripcionParameter, juzg_fecharecepcionParameter, juzg_pronunciamientoParameter, juzg_fechaderivacionParameter, juzg_fechaemisionresolParameter, juzg_fechanotificacionParameter, juzg_fechasolucionParameter);
        }
    
        public virtual int insertar_MovExp(Nullable<int> movexp_id, Nullable<int> ab_id, Nullable<int> usu_id, Nullable<int> demte_id, Nullable<int> demdo_id, Nullable<int> anexo_id, string movexp_asunto, Nullable<System.DateTime> movexp_fechaing, string movexp_estado, string movexp_progreso, string movexp_cantfolios, string movexp_descripcion)
        {
            var movexp_idParameter = movexp_id.HasValue ?
                new ObjectParameter("movexp_id", movexp_id) :
                new ObjectParameter("movexp_id", typeof(int));
    
            var ab_idParameter = ab_id.HasValue ?
                new ObjectParameter("ab_id", ab_id) :
                new ObjectParameter("ab_id", typeof(int));
    
            var usu_idParameter = usu_id.HasValue ?
                new ObjectParameter("usu_id", usu_id) :
                new ObjectParameter("usu_id", typeof(int));
    
            var demte_idParameter = demte_id.HasValue ?
                new ObjectParameter("demte_id", demte_id) :
                new ObjectParameter("demte_id", typeof(int));
    
            var demdo_idParameter = demdo_id.HasValue ?
                new ObjectParameter("demdo_id", demdo_id) :
                new ObjectParameter("demdo_id", typeof(int));
    
            var anexo_idParameter = anexo_id.HasValue ?
                new ObjectParameter("anexo_id", anexo_id) :
                new ObjectParameter("anexo_id", typeof(int));
    
            var movexp_asuntoParameter = movexp_asunto != null ?
                new ObjectParameter("movexp_asunto", movexp_asunto) :
                new ObjectParameter("movexp_asunto", typeof(string));
    
            var movexp_fechaingParameter = movexp_fechaing.HasValue ?
                new ObjectParameter("movexp_fechaing", movexp_fechaing) :
                new ObjectParameter("movexp_fechaing", typeof(System.DateTime));
    
            var movexp_estadoParameter = movexp_estado != null ?
                new ObjectParameter("movexp_estado", movexp_estado) :
                new ObjectParameter("movexp_estado", typeof(string));
    
            var movexp_progresoParameter = movexp_progreso != null ?
                new ObjectParameter("movexp_progreso", movexp_progreso) :
                new ObjectParameter("movexp_progreso", typeof(string));
    
            var movexp_cantfoliosParameter = movexp_cantfolios != null ?
                new ObjectParameter("movexp_cantfolios", movexp_cantfolios) :
                new ObjectParameter("movexp_cantfolios", typeof(string));
    
            var movexp_descripcionParameter = movexp_descripcion != null ?
                new ObjectParameter("movexp_descripcion", movexp_descripcion) :
                new ObjectParameter("movexp_descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_MovExp", movexp_idParameter, ab_idParameter, usu_idParameter, demte_idParameter, demdo_idParameter, anexo_idParameter, movexp_asuntoParameter, movexp_fechaingParameter, movexp_estadoParameter, movexp_progresoParameter, movexp_cantfoliosParameter, movexp_descripcionParameter);
        }
    
        public virtual int insertar_Persona(Nullable<int> pers_id, string pers_nombres, string pers_ciudad, string pers_provincia, string pers_departamento, string pers_ubigeo, string pers_domlegal, string pers_telefono, string pers_email, Nullable<int> id_tipdoc, Nullable<decimal> pers_numdoc)
        {
            var pers_idParameter = pers_id.HasValue ?
                new ObjectParameter("pers_id", pers_id) :
                new ObjectParameter("pers_id", typeof(int));
    
            var pers_nombresParameter = pers_nombres != null ?
                new ObjectParameter("pers_nombres", pers_nombres) :
                new ObjectParameter("pers_nombres", typeof(string));
    
            var pers_ciudadParameter = pers_ciudad != null ?
                new ObjectParameter("pers_ciudad", pers_ciudad) :
                new ObjectParameter("pers_ciudad", typeof(string));
    
            var pers_provinciaParameter = pers_provincia != null ?
                new ObjectParameter("pers_provincia", pers_provincia) :
                new ObjectParameter("pers_provincia", typeof(string));
    
            var pers_departamentoParameter = pers_departamento != null ?
                new ObjectParameter("pers_departamento", pers_departamento) :
                new ObjectParameter("pers_departamento", typeof(string));
    
            var pers_ubigeoParameter = pers_ubigeo != null ?
                new ObjectParameter("pers_ubigeo", pers_ubigeo) :
                new ObjectParameter("pers_ubigeo", typeof(string));
    
            var pers_domlegalParameter = pers_domlegal != null ?
                new ObjectParameter("pers_domlegal", pers_domlegal) :
                new ObjectParameter("pers_domlegal", typeof(string));
    
            var pers_telefonoParameter = pers_telefono != null ?
                new ObjectParameter("pers_telefono", pers_telefono) :
                new ObjectParameter("pers_telefono", typeof(string));
    
            var pers_emailParameter = pers_email != null ?
                new ObjectParameter("pers_email", pers_email) :
                new ObjectParameter("pers_email", typeof(string));
    
            var id_tipdocParameter = id_tipdoc.HasValue ?
                new ObjectParameter("id_tipdoc", id_tipdoc) :
                new ObjectParameter("id_tipdoc", typeof(int));
    
            var pers_numdocParameter = pers_numdoc.HasValue ?
                new ObjectParameter("pers_numdoc", pers_numdoc) :
                new ObjectParameter("pers_numdoc", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_Persona", pers_idParameter, pers_nombresParameter, pers_ciudadParameter, pers_provinciaParameter, pers_departamentoParameter, pers_ubigeoParameter, pers_domlegalParameter, pers_telefonoParameter, pers_emailParameter, id_tipdocParameter, pers_numdocParameter);
        }
    
        public virtual int insertar_TipAbg(Nullable<int> tipb_id, string tipb_def_inc, string tipb_estado, string tipb_descripcion)
        {
            var tipb_idParameter = tipb_id.HasValue ?
                new ObjectParameter("tipb_id", tipb_id) :
                new ObjectParameter("tipb_id", typeof(int));
    
            var tipb_def_incParameter = tipb_def_inc != null ?
                new ObjectParameter("tipb_def_inc", tipb_def_inc) :
                new ObjectParameter("tipb_def_inc", typeof(string));
    
            var tipb_estadoParameter = tipb_estado != null ?
                new ObjectParameter("tipb_estado", tipb_estado) :
                new ObjectParameter("tipb_estado", typeof(string));
    
            var tipb_descripcionParameter = tipb_descripcion != null ?
                new ObjectParameter("tipb_descripcion", tipb_descripcion) :
                new ObjectParameter("tipb_descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_TipAbg", tipb_idParameter, tipb_def_incParameter, tipb_estadoParameter, tipb_descripcionParameter);
        }
    
        public virtual int insertar_Tipodoc(Nullable<int> id_tipdoc, string tipdoc_nom)
        {
            var id_tipdocParameter = id_tipdoc.HasValue ?
                new ObjectParameter("id_tipdoc", id_tipdoc) :
                new ObjectParameter("id_tipdoc", typeof(int));
    
            var tipdoc_nomParameter = tipdoc_nom != null ?
                new ObjectParameter("tipdoc_nom", tipdoc_nom) :
                new ObjectParameter("tipdoc_nom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_Tipodoc", id_tipdocParameter, tipdoc_nomParameter);
        }
    
        public virtual int insertar_TipUsu(Nullable<int> tipusu_id, string tipusu_tipousuario, string tipusu_descripcion)
        {
            var tipusu_idParameter = tipusu_id.HasValue ?
                new ObjectParameter("tipusu_id", tipusu_id) :
                new ObjectParameter("tipusu_id", typeof(int));
    
            var tipusu_tipousuarioParameter = tipusu_tipousuario != null ?
                new ObjectParameter("tipusu_tipousuario", tipusu_tipousuario) :
                new ObjectParameter("tipusu_tipousuario", typeof(string));
    
            var tipusu_descripcionParameter = tipusu_descripcion != null ?
                new ObjectParameter("tipusu_descripcion", tipusu_descripcion) :
                new ObjectParameter("tipusu_descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_TipUsu", tipusu_idParameter, tipusu_tipousuarioParameter, tipusu_descripcionParameter);
        }
    
        public virtual int insertar_Usu(Nullable<int> usu_id, Nullable<int> tipusu_id, string usu_dni, string usu_nombres, string usu_apellidopat, string usu_apellidomat, string usu_telefono, string usu_direccion, string usu_sexo, string usu_correo, string usu_estadocivil, Nullable<System.DateTime> usu_fechanac, string usu_ciudad, string usu_provincia, Nullable<int> id_estusu, string usu_departamento, string usu_contraseña)
        {
            var usu_idParameter = usu_id.HasValue ?
                new ObjectParameter("usu_id", usu_id) :
                new ObjectParameter("usu_id", typeof(int));
    
            var tipusu_idParameter = tipusu_id.HasValue ?
                new ObjectParameter("tipusu_id", tipusu_id) :
                new ObjectParameter("tipusu_id", typeof(int));
    
            var usu_dniParameter = usu_dni != null ?
                new ObjectParameter("usu_dni", usu_dni) :
                new ObjectParameter("usu_dni", typeof(string));
    
            var usu_nombresParameter = usu_nombres != null ?
                new ObjectParameter("usu_nombres", usu_nombres) :
                new ObjectParameter("usu_nombres", typeof(string));
    
            var usu_apellidopatParameter = usu_apellidopat != null ?
                new ObjectParameter("usu_apellidopat", usu_apellidopat) :
                new ObjectParameter("usu_apellidopat", typeof(string));
    
            var usu_apellidomatParameter = usu_apellidomat != null ?
                new ObjectParameter("usu_apellidomat", usu_apellidomat) :
                new ObjectParameter("usu_apellidomat", typeof(string));
    
            var usu_telefonoParameter = usu_telefono != null ?
                new ObjectParameter("usu_telefono", usu_telefono) :
                new ObjectParameter("usu_telefono", typeof(string));
    
            var usu_direccionParameter = usu_direccion != null ?
                new ObjectParameter("usu_direccion", usu_direccion) :
                new ObjectParameter("usu_direccion", typeof(string));
    
            var usu_sexoParameter = usu_sexo != null ?
                new ObjectParameter("usu_sexo", usu_sexo) :
                new ObjectParameter("usu_sexo", typeof(string));
    
            var usu_correoParameter = usu_correo != null ?
                new ObjectParameter("usu_correo", usu_correo) :
                new ObjectParameter("usu_correo", typeof(string));
    
            var usu_estadocivilParameter = usu_estadocivil != null ?
                new ObjectParameter("usu_estadocivil", usu_estadocivil) :
                new ObjectParameter("usu_estadocivil", typeof(string));
    
            var usu_fechanacParameter = usu_fechanac.HasValue ?
                new ObjectParameter("usu_fechanac", usu_fechanac) :
                new ObjectParameter("usu_fechanac", typeof(System.DateTime));
    
            var usu_ciudadParameter = usu_ciudad != null ?
                new ObjectParameter("usu_ciudad", usu_ciudad) :
                new ObjectParameter("usu_ciudad", typeof(string));
    
            var usu_provinciaParameter = usu_provincia != null ?
                new ObjectParameter("usu_provincia", usu_provincia) :
                new ObjectParameter("usu_provincia", typeof(string));
    
            var id_estusuParameter = id_estusu.HasValue ?
                new ObjectParameter("id_estusu", id_estusu) :
                new ObjectParameter("id_estusu", typeof(int));
    
            var usu_departamentoParameter = usu_departamento != null ?
                new ObjectParameter("usu_departamento", usu_departamento) :
                new ObjectParameter("usu_departamento", typeof(string));
    
            var usu_contraseñaParameter = usu_contraseña != null ?
                new ObjectParameter("usu_contraseña", usu_contraseña) :
                new ObjectParameter("usu_contraseña", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertar_Usu", usu_idParameter, tipusu_idParameter, usu_dniParameter, usu_nombresParameter, usu_apellidopatParameter, usu_apellidomatParameter, usu_telefonoParameter, usu_direccionParameter, usu_sexoParameter, usu_correoParameter, usu_estadocivilParameter, usu_fechanacParameter, usu_ciudadParameter, usu_provinciaParameter, id_estusuParameter, usu_departamentoParameter, usu_contraseñaParameter);
        }
    
        public virtual int InsertarAnexos(Nullable<int> id_anexo, string anexo_nombre, string anexo_nombrereal, byte[] anexo_documento, Nullable<System.DateTime> anexo_fecha)
        {
            var id_anexoParameter = id_anexo.HasValue ?
                new ObjectParameter("id_anexo", id_anexo) :
                new ObjectParameter("id_anexo", typeof(int));
    
            var anexo_nombreParameter = anexo_nombre != null ?
                new ObjectParameter("anexo_nombre", anexo_nombre) :
                new ObjectParameter("anexo_nombre", typeof(string));
    
            var anexo_nombrerealParameter = anexo_nombrereal != null ?
                new ObjectParameter("anexo_nombrereal", anexo_nombrereal) :
                new ObjectParameter("anexo_nombrereal", typeof(string));
    
            var anexo_documentoParameter = anexo_documento != null ?
                new ObjectParameter("anexo_documento", anexo_documento) :
                new ObjectParameter("anexo_documento", typeof(byte[]));
    
            var anexo_fechaParameter = anexo_fecha.HasValue ?
                new ObjectParameter("anexo_fecha", anexo_fecha) :
                new ObjectParameter("anexo_fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertarAnexos", id_anexoParameter, anexo_nombreParameter, anexo_nombrerealParameter, anexo_documentoParameter, anexo_fechaParameter);
        }
    
        public virtual int NuevaContrasena(string correo, string contrasena)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NuevaContrasena", correoParameter, contrasenaParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<ValidarCorreo_Result> ValidarCorreo(string correo)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ValidarCorreo_Result>("ValidarCorreo", correoParameter);
        }
    }
}
