//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solucion_informatica_Consultorio_Juridico.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expediente
    {
        public int exp_id { get; set; }
        public int movexp_id { get; set; }
        public int juzg_id { get; set; }
        public int doc_id { get; set; }
        public string exp_nrosentencia { get; set; }
        public string exp_expediente { get; set; }
        public string exp_secrejuzg { get; set; }
        public Nullable<System.DateTime> exp_fechainicio { get; set; }
        public string exp_materia { get; set; }
        public string exp_resolucionnro { get; set; }
        public string exp_ciudad { get; set; }
        public Nullable<System.DateTime> exp_fecha { get; set; }
        public string exp_vistos { get; set; }
    
        public virtual Documento Documento { get; set; }
        public virtual Historial_Juzgado Historial_Juzgado { get; set; }
        public virtual Movimiento_Expediente Movimiento_Expediente { get; set; }
    }
}
