//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solucion_informatica_Consultorio_Juridico.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial_Juzgado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Historial_Juzgado()
        {
            this.Expediente = new HashSet<Expediente>();
        }
    
        public int juzg_id { get; set; }
        public string juzg_descripcion { get; set; }
        public Nullable<System.DateTime> juzg_fecharecepcion { get; set; }
        public string juzg_pronunciamiento { get; set; }
        public Nullable<System.DateTime> juzg_fechaderivacion { get; set; }
        public Nullable<System.DateTime> juzg_fechaemisionresol { get; set; }
        public Nullable<System.DateTime> juzg_fechanotificacion { get; set; }
        public Nullable<System.DateTime> juzg_fechasolucion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expediente> Expediente { get; set; }
    }
}
