//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solucion_informatica_Consultorio_Juridico.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logueo
    {
        public int usu_log { get; set; }
        public int usu_id { get; set; }
        public int tipusu_id { get; set; }
        public string log_username { get; set; }
        public string log_contraseña { get; set; }
    }
}
