//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solucion_informatica_Consultorio_Juridico.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento_Expediente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movimiento_Expediente()
        {
            this.Expediente = new HashSet<Expediente>();
        }
    
        public int movexp_id { get; set; }
        public int ab_id { get; set; }
        public int usu_id { get; set; }
        public int demte_id { get; set; }
        public int demdo_id { get; set; }
        public int anexo_id { get; set; }
        public string movexp_asunto { get; set; }
        public Nullable<System.DateTime> movexp_fechaing { get; set; }
        public string movexp_estado { get; set; }
        public string movexp_progreso { get; set; }
        public string movexp_cantfolios { get; set; }
        public string movexp_descripcion { get; set; }
    
        public virtual Abogado Abogado { get; set; }
        public virtual Abogado Abogado1 { get; set; }
        public virtual Anexos Anexos { get; set; }
        public virtual Demandado Demandado { get; set; }
        public virtual Demandante Demandante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expediente> Expediente { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
