//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solucion_informatica_Consultorio_Juridico.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Demandado = new HashSet<Demandado>();
            this.Demandante = new HashSet<Demandante>();
        }
    
        public int pers_id { get; set; }
        public string pers_nombres { get; set; }
        public string pers_ciudad { get; set; }
        public string pers_provincia { get; set; }
        public string pers_departamento { get; set; }
        public string pers_ubigeo { get; set; }
        public string pers_domlegal { get; set; }
        public string pers_telefono { get; set; }
        public string pers_email { get; set; }
        public int id_tipdoc { get; set; }
        public decimal pers_numdoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Demandado> Demandado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Demandante> Demandante { get; set; }
        public virtual Tip_documento Tip_documento { get; set; }
    }
}
