//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solucion_informatica_Consultorio_Juridico.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_lstperxtipdoc
    {
        public int pers_id { get; set; }
        public string tipdoc_nom { get; set; }
        public string pers_nombres { get; set; }
        public string pers_ubigeo { get; set; }
        public string pers_telefono { get; set; }
        public string pers_email { get; set; }
        public decimal pers_numdoc { get; set; }
    }
}
