//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solucion_informatica_Consultorio_Juridico.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_lstexpxmovexp
    {
        public int exp_id { get; set; }
        public int movexp_id { get; set; }
        public string movexp_asunto { get; set; }
        public Nullable<System.DateTime> movexp_fechaing { get; set; }
        public string movexp_estado { get; set; }
        public string movexp_progreso { get; set; }
        public string movexp_descripcion { get; set; }
        public string exp_nrosentencia { get; set; }
        public string exp_expediente { get; set; }
        public string exp_secrejuzg { get; set; }
        public string exp_materia { get; set; }
        public Nullable<System.DateTime> exp_fechainicio { get; set; }
    }
}
