//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solucion_informatica_Consultorio_Juridico.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_lsttipabxabo
    {
        public int tipb_id { get; set; }
        public string tipb_def_inc { get; set; }
        public string tipb_descripcion { get; set; }
        public string ab_nombres { get; set; }
        public string ab_apellidopat { get; set; }
        public string ab_apellidomat { get; set; }
        public string ab_dni { get; set; }
    }
}
