//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solucion_informatica_Consultorio_Juridico.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_lstjuzgxexp
    {
        public int juzg_id { get; set; }
        public string exp_nrosentencia { get; set; }
        public string exp_expediente { get; set; }
        public string exp_secrejuzg { get; set; }
        public Nullable<System.DateTime> exp_fechainicio { get; set; }
        public string exp_materia { get; set; }
        public string exp_resolucionnro { get; set; }
        public string juzg_descripcion { get; set; }
        public Nullable<System.DateTime> juzg_fecharecepcion { get; set; }
        public string juzg_pronunciamiento { get; set; }
        public Nullable<System.DateTime> juzg_fechaderivacion { get; set; }
        public Nullable<System.DateTime> juzg_fechanotificacion { get; set; }
        public Nullable<System.DateTime> juzg_fechaemisionresol { get; set; }
        public Nullable<System.DateTime> juzg_fechasolucion { get; set; }
    }
}
